# Generated by Django 4.2.13 on 2025-03-21 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='idCircunscripcion',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='voto',
            name='idMesaElectoral',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='voto',
            name='idProcesoElectoral',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='voto',
            name='nombreCandidatoVotado',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
